name: Sync to Hugging Face Space
on:
  push:
    branches: [main]
  force_push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        # Menggunakan Action resmi dari Hugging Face untuk mengirim folder tertentu
        uses: huggingface/github-action@v1
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_id: wildan14/agriflow
          repo_type: space
          # Folder yang isinya ingin kita jadikan "Halaman Utama" di HF
          folder: agriflow-backend
