name: Sync to Hugging Face Space
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://user:$HF_TOKEN@huggingface.co/spaces/wildan14/agriflow hf_space
          rsync -av --delete agriflow-backend/ hf_space/ --exclude .git
          cd hf_space
          git add .
          git commit -m "Auto-deploy from GitHub" || echo "No changes to commit"
          git push https://user:$HF_TOKEN@huggingface.co/spaces/wildan14/agriflow main
