name: Sync to Hugging Face Space
on:
  push:
    branches: [main] # Updated to main branch
  force_push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configure User
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Add HF Remote
          git remote add hf https://wildan14:$HF_TOKEN@huggingface.co/spaces/wildan14/agriflow
          
          # Push agriflow-backend folder contents to HF root (main branch)
          git subtree push --prefix agriflow-backend hf main --force
